In [37]:
import pandas as pd
import numpy as np
import seaborn as sns

In [29]:
# Issues arise because of the encoding, using latin1 because of the 0x1f in the error showing

Windturbine=pd.read_csv('./windturbine20220114.csv',engine='python',encoding='latin1')

# Make a copy of original csv
Windturbinecopy=Windturbine.copy()

In [31]:
Windturbine

,case_id,faa_ors,faa_asn,usgs_pr_id,eia_id,t_state,t_county,t_fips,p_name,p_year,...,t_rsa,t_ttlh,retrofit,retrofit_year,t_conf_atr,t_conf_loc,t_img_date,t_img_srce,xlong,ylat
0,3072661,NaN,NaN,5149.0,52161.0,CA,Kern County,6029,251 Wind,1987.0,...,NaN,NaN,0,NaN,2,3,5/8/2018,Digital Globe,-118.363762,35.077908
1,3072695,NaN,NaN,5143.0,52161.0,CA,Kern County,6029,251 Wind,1987.0,...,NaN,NaN,0,NaN,2,3,5/8/2018,Digital Globe,-118.364410,35.077435
2,3072704,NaN,NaN,5146.0,52161.0,CA,Kern County,6029,251 Wind,1987.0,...,NaN,NaN,0,NaN,2,3,5/8/2018,Digital Globe,-118.364197,35.077644
3,3063272,19-028134,2014-WTE-4084-OE,NaN,NaN,IA,Story County,19169,30 MW Iowa DG Portfolio,2017.0,...,12271.85,150.0,0,NaN,3,3,4/24/2017,Digital Globe,-93.430367,42.028233
4,3053390,19-028015,2015-WTE-6386-OE,NaN,NaN,IA,Boone County,19015,30 MW Iowa DG Portfolio,2017.0,...,12271.85,150.0,0,NaN,3,3,6/1/2017,Digital Globe,-93.700424,41.977608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70803,3053232,36-120351,2015-WTE-5788-OE,NaN,NaN,NY,Wyoming County,36121,unknown Wyoming County,2016.0,...,NaN,NaN,0,NaN,1,3,5/20/2017,Digital Globe,-78.187935,42.740818
70804,3101958,48-171972,2020-WTW-2021-OE,NaN,NaN,TX,Young County,48503,unknown Young County,NaN,...,NaN,NaN,0,NaN,1,1,8/2/2020,Digital Globe,-98.907600,33.149414
70805,3040944,48-024978,2011-WTW-352-OE,41364.0,NaN,TX,Young County,48503,unknown Young County 1,2011.0,...,NaN,NaN,0,NaN,1,3,7/16/2018,Digital Globe,-98.551094,33.093292
70806,3055918,08-072237,2015-WTW-9995-OE,NaN,NaN,CO,Yuma County,8125,unknown Yuma County,2016.0,...,NaN,NaN,0,NaN,1,3,5/17/2017,Digital Globe,-102.716949,40.037548
70807,3055917,08-072245,2015-WTW-9994-OE,NaN,NaN,CO,Yuma County,8125,unknown Yuma County,2016.0,...,NaN,NaN,0,NaN,1,3,5/17/2017,Digital Globe,-102.717171,40.035072

In [27]:
# Count all null rows from the table
Windturbine.isnull().sum()

case_id              0
faa_ors           5792
faa_asn           5122
usgs_pr_id       32545
eia_id            5793
t_state              0
t_county             0
t_fips               0
p_name               0
p_year             613
p_tnum               0
p_cap             4482
t_manu            5640
t_model           5777
t_cap             5480
t_hh              6180
t_rd              5934
t_rsa             5934
t_ttlh            6180
retrofit             0
retrofit_year    64822
t_conf_atr           0
t_conf_loc           0
t_img_date        8316
t_img_srce           0
xlong                0
ylat                 0
dtype: int64

In [28]:
Windturbine.describe()

,case_id,usgs_pr_id,eia_id,t_fips,p_year,p_tnum,p_cap,t_cap,t_hh,t_rd,t_rsa,t_ttlh,retrofit,retrofit_year,t_conf_atr,t_conf_loc,xlong,ylat
count,7.080800e+04,38263.000000,65015.000000,70808.000000,70195.000000,70808.000000,66326.000000,65328.000000,64628.000000,64874.000000,64874.000000,64628.000000,70808.000000,5986.000000,70808.000000,70808.000000,70808.000000,70808.000000
mean,3.058490e+06,27523.587225,57877.751642,32244.494097,2011.650659,104.360552,170.176128,1963.534151,81.054571,95.663717,7618.500657,129.050593,0.084538,2018.640327,2.766509,2.883784,-100.086457,38.479503
std,3.242377e+04,13564.446593,5984.516487,15498.246596,7.879099,93.954786,104.478693,717.067912,12.028726,23.424346,3309.229282,22.185981,0.278196,1.112294,0.597195,0.462326,11.141025,5.429730
min,3.000001e+06,1.000000,90.000000,2013.000000,1981.000000,1.000000,0.050000,50.000000,19.000000,13.400000,141.030000,30.400000,0.000000,2015.000000,1.000000,1.000000,-171.713074,13.389381
25%,3.032230e+06,18625.500000,56763.000000,19081.000000,2008.000000,56.000000,99.000000,1500.000000,80.000000,82.000000,5281.020000,121.000000,0.000000,2018.000000,3.000000,3.000000,-103.037155,34.428043
50%,3.050978e+06,28598.000000,57752.000000,35057.000000,2012.000000,85.000000,158.000000,2000.000000,80.000000,100.000000,7853.980000,130.100000,0.000000,2019.000000,3.000000,3.000000,-99.393761,39.052442
75%,3.090448e+06,38719.500000,60338.000000,48141.000000,2018.000000,121.000000,211.220000,2300.000000,87.000000,110.000000,9503.320000,145.100000,0.000000,2020.000000,3.000000,3.000000,-95.202499,42.812810
max,3.118671e+06,49135.000000,65270.000000,72133.000000,2021.000000,731.000000,525.020000,6000.000000,131.000000,155.000000,18869.190000,199.600000,1.000000,2020.000000,3.000000,3.000000,144.722656,66.839905

In [33]:
# Drop column faa_ors (Unique identifier for cross-reference to the Federal Aviation Administration (FAA) digital obstacle files).
# Drop column faa_asn (Unique identifier for cross-reference to the FAA obstruction evaluation airport airspace analysis dataset).
# Drop the entire column usgs_pr_id (Unique identifier for cross-reference to the 2014 USGS turbine dataset)
# Keep eid_id, p_year,p_cap....t_ttlh
# Drop both t_img_date & t_img_srce
# Drop t_conf_atr & t_conf_loc

Windturbine.drop(['faa_ors','faa_asn','usgs_pr_id','t_img_date','t_img_srce','t_conf_atr','t_conf_loc'],axis=1,inplace=True)

In [51]:
Windturbine.describe()

,case_id,eia_id,t_state,t_county,t_fips,p_name,p_year,p_tnum,p_cap,t_manu,t_model,t_cap,t_hh,t_rd,t_rsa,t_ttlh,retrofit,retrofit_year,xlong,ylat
0,3072661,52161.0,CA,Kern County,6029,251 Wind,1987.0,194,18.43,Vestas,NaN,95.0,NaN,NaN,NaN,NaN,0,NaN,-118.363762,35.077908
1,3072695,52161.0,CA,Kern County,6029,251 Wind,1987.0,194,18.43,Vestas,NaN,95.0,NaN,NaN,NaN,NaN,0,NaN,-118.364410,35.077435
2,3072704,52161.0,CA,Kern County,6029,251 Wind,1987.0,194,18.43,Vestas,NaN,95.0,NaN,NaN,NaN,NaN,0,NaN,-118.364197,35.077644
3,3063272,NaN,IA,Story County,19169,30 MW Iowa DG Portfolio,2017.0,10,30.00,Nordex,AW125/3000,3000.0,87.5,125.0,12271.85,150.0,0,NaN,-93.430367,42.028233
4,3053390,NaN,IA,Boone County,19015,30 MW Iowa DG Portfolio,2017.0,10,30.00,Nordex,AW125/3000,3000.0,87.5,125.0,12271.85,150.0,0,NaN,-93.700424,41.977608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70803,3053232,NaN,NY,Wyoming County,36121,unknown Wyoming County,2016.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,-78.187935,42.740818
70804,3101958,NaN,TX,Young County,48503,unknown Young County,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,-98.907600,33.149414
70805,3040944,NaN,TX,Young County,48503,unknown Young County 1,2011.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,-98.551094,33.093292
70806,3055918,NaN,CO,Yuma County,8125,unknown Yuma County,2016.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,-102.716949,40.037548
70807,3055917,NaN,CO,Yuma County,8125,unknown Yuma County,2016.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,-102.717171,40.035072

Based on data distribution, we have applied
median values to p_cap, t_cap, t_hh, t_rd and t_ttlh
mean value to t_rsa

In [56]:
givevalues = {"p_cap": 158, "t_cap": 2000, "t_hh": 80, "t_rd": 100,"t_rsa": 7618.5,"t_ttlh": 130.1}

Windturbine.fillna(value=givevalues,inplace=True)

In [58]:
# Check if there is any duplicate values in case_id
Windturbine['case_id'].is_unique

True

In [61]:
Windturbine.to_csv (r'.\Cleaned_Windturbine.csv', index = False, header=True)